### ISSUE TITLE
Undefined index: filters

### ISSUE THREAD

**Issue by floriankraemer** [spryker-sdk/brancho#5]
Even after installing Brancho globally, I get this error. The error happens when running `brancho branch`, doesn't matter where I run it in the file system.

A quick investigation has shown that the problem seems to be that the config is not loaded. In fact, there is no config it can load, nor did it generate one or is falling back to default config.

My proposed fix is to check if the file exists, if it doesn't create it with default values. The alternative would be to have the minimum default config present in the classes config and just overriding / merging it when a config file is loaded.

```
florian@DESKTOP-G2G94QK:~/projects/my-project/vendor/spryker/spryker$ brancho branch
PHP Notice:  Undefined index: filters in /home/florian/.config/composer/vendor/spryker-sdk/brancho/src/Brancho/Brancho.php on line 137
PHP Warning:  Invalid argument supplied for foreach() in /home/florian/.config/composer/vendor/spryker-sdk/brancho/src/Brancho/Brancho.php on line 137
PHP Notice:  Undefined index: resolver in /home/florian/.config/composer/vendor/spryker-sdk/brancho/src/Brancho/Brancho.php on line 113
PHP Fatal error:  Uncaught Error: Class name must be a valid object or a string in /home/florian/.config/composer/vendor/spryker-sdk/brancho/src/Brancho/Brancho.php:113
Stack trace:
#0 /home/florian/.config/composer/vendor/spryker-sdk/brancho/src/Brancho/Brancho.php(62): Brancho\Brancho->getResolver(Array)
#1 /home/florian/.config/composer/vendor/spryker-sdk/brancho/src/Brancho/Command/BranchBuilderCommand.php(50): Brancho\Brancho->resolveBranchNames(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /home/florian/.config/composer/vendor/symfony/console/Command/Command.php(288): Brancho\Command\BranchBuilderCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /home/florian/.config/composer/vendor/symfony/console/Application.php(974): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /home/fl in /home/florian/.config/composer/vendor/spryker-sdk/brancho/src/Brancho/Brancho.php on line 113
```

**Comment by dereuromark** [comment]
Can you make a quick pr here?

**Comment by floriankraemer** [comment]
@dereuromark done.
